"""
PDF Report Generation module for VYRO using ReportLab.
Transforms a ReviewResult Pydantic model into a polished, printable Review Report.
Includes automatic paragraph wrapping in table cells, severity color-coding,
follow-up questions, and a persistent footer: 'Generated by VYRO. AI assists, humans decide.'
"""
import io
from datetime import datetime
from typing import List

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas
from models import ReviewResult, Issue


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute total page count and draw
    a professional footer on every page.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, total_pages: int):
        self.saveState()
        
        # Bottom divider rule
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.75)
        self.line(36, 38, 612 - 36, 38)
        
        # Left footer: Mandatory system statement
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#475569"))
        self.drawString(36, 26, "Generated by VYRO. AI assists, humans decide.")
        
        # Right footer: Page numbering
        page_str = f"Page {self._pageNumber} of {total_pages}"
        self.drawRightString(612 - 36, 26, page_str)
        
        self.restoreState()


def generate_review_pdf(result: ReviewResult) -> bytes:
    """
    Generates a PDF Review Report from a ReviewResult using ReportLab.

    Parameters:
        result (ReviewResult): Validated review audit results.

    Returns:
        bytes: Raw PDF file bytes for download.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=48
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#0f172a")
    )

    h2_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#0f172a"),
        spaceBefore=12,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        "BodyDark",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#1e293b")
    )

    meta_label = ParagraphStyle(
        "MetaLabel",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#475569")
    )

    meta_value = ParagraphStyle(
        "MetaVal",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#0f172a")
    )

    table_cell = ParagraphStyle(
        "TableCell",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor("#1e293b")
    )

    table_header = ParagraphStyle(
        "TableHeader",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=10,
        textColor=colors.white
    )

    question_item = ParagraphStyle(
        "QuestionItem",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=12.5,
        textColor=colors.HexColor("#0f172a")
    )

    story = []

    # 1. HEADER SECTION
    # Brand title with emerald highlight
    story.append(Paragraph("<font color='#16a34a'><b>VYRO</b></font> &mdash; Environmental Clearance Review Report", title_style))
    story.append(Paragraph("<font color='#64748b' size='9'>AI-Assisted Completeness & Internal Consistency Audit</font>", body_style))
    story.append(Spacer(1, 10))

    # Metadata Grid
    now_str = datetime.now().strftime("%B %d, %Y &bull; %H:%M")
    r_score = getattr(result, "readiness_score", None) if getattr(result, "readiness_score", None) is not None else result.completeness_score
    r_band = getattr(result, "readiness_band", None) or ("High" if r_score >= 85 else ("Moderate" if r_score >= 65 else "Low"))
    r_low = getattr(result, "readiness_range_low", None) if getattr(result, "readiness_range_low", None) is not None else r_score
    r_high = getattr(result, "readiness_range_high", None) if getattr(result, "readiness_range_high", None) is not None else r_score

    meta_data = [
        [Paragraph("<b>Project Name:</b>", meta_label), Paragraph(result.project_name, meta_value),
         Paragraph("<b>Audit Date:</b>", meta_label), Paragraph(now_str, meta_value)],
        [Paragraph("<b>Readiness Score:</b>", meta_label), Paragraph(f"<b>{r_score}%</b> ({r_band} Band)", meta_value),
         Paragraph("<b>Estimated Range:</b>", meta_label), Paragraph(f"[{r_low}% &ndash; {r_high}%]", meta_value)]
    ]
    meta_table = Table(meta_data, colWidths=[90, 200, 80, 170])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
        ('BOX', (0, 0), (-1, -1), 0.75, colors.HexColor("#e2e8f0")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#f1f5f9")),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 10))

    # 2. EXECUTIVE SUMMARY
    story.append(Paragraph("1. Executive Summary", h2_style))
    summary_box = Table([[Paragraph(result.summary, body_style)]], colWidths=[540])
    summary_box.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
        ('BOX', (0, 0), (-1, -1), 0.75, colors.HexColor("#cbd5e1")),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
    ]))
    story.append(summary_box)
    story.append(Spacer(1, 10))

    # 3. STATUTORY CLEARANCE READINESS APPRAISAL
    story.append(Paragraph("2. Statutory Clearance Readiness Appraisal (18 MoEFCC Rules)", h2_style))
    
    # Readiness Score Box
    score_tint = colors.HexColor("#dcfce7") if r_band == "High" else (colors.HexColor("#dbeafe") if r_band == "Moderate" else colors.HexColor("#ffedd5"))
    score_border = colors.HexColor("#16a34a") if r_band == "High" else (colors.HexColor("#2563eb") if r_band == "Moderate" else colors.HexColor("#ea580c"))
    score_text = f"<b>Readiness Score: {r_score}% &nbsp;|&nbsp; Band: {r_band.upper()} &nbsp;|&nbsp; Uncertainty Range: [{r_low}% &ndash; {r_high}%]</b>"
    
    readiness_box = Table([[Paragraph(score_text, body_style)]], colWidths=[540])
    readiness_box.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), score_tint),
        ('BOX', (0, 0), (-1, -1), 1.0, score_border),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
    ]))
    story.append(readiness_box)
    story.append(Spacer(1, 6))

    # Category Counts Table
    cc = getattr(result, "readiness_category_counts", None) or {}
    crit_c = cc.get("Critical", {"pass": 0, "partial": 0, "fail": 0, "not_found": 0, "total": 6})
    maj_c = cc.get("Major", {"pass": 0, "partial": 0, "fail": 0, "not_found": 0, "total": 8})
    min_c = cc.get("Minor", {"pass": 0, "partial": 0, "fail": 0, "not_found": 0, "total": 4})

    cat_rows = [
        [Paragraph("Category (Weight)", meta_label), Paragraph("Pass", meta_label), Paragraph("Partial", meta_label), Paragraph("Fail", meta_label), Paragraph("Missing", meta_label), Paragraph("Total", meta_label)],
        [Paragraph("Critical Rules (w=3)", body_style), Paragraph(str(crit_c.get("pass", 0)), body_style), Paragraph(str(crit_c.get("partial", 0)), body_style), Paragraph(str(crit_c.get("fail", 0)), body_style), Paragraph(str(crit_c.get("not_found", 0)), body_style), Paragraph(str(crit_c.get("total", 6)), body_style)],
        [Paragraph("Major Rules (w=2)", body_style), Paragraph(str(maj_c.get("pass", 0)), body_style), Paragraph(str(maj_c.get("partial", 0)), body_style), Paragraph(str(maj_c.get("fail", 0)), body_style), Paragraph(str(maj_c.get("not_found", 0)), body_style), Paragraph(str(maj_c.get("total", 8)), body_style)],
        [Paragraph("Minor Rules (w=1)", body_style), Paragraph(str(min_c.get("pass", 0)), body_style), Paragraph(str(min_c.get("partial", 0)), body_style), Paragraph(str(min_c.get("fail", 0)), body_style), Paragraph(str(min_c.get("not_found", 0)), body_style), Paragraph(str(min_c.get("total", 4)), body_style)],
    ]
    cat_table = Table(cat_rows, colWidths=[160, 75, 75, 75, 75, 80])
    cat_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(cat_table)
    story.append(Spacer(1, 6))

    # Top Improvements
    improvements = getattr(result, "readiness_improvements", None) or []
    if improvements:
        story.append(Paragraph("<b>Top Priority Recommendations to Improve Score:</b>", meta_label))
        for imp in improvements[:3]:
            gain_txt = f"<font color='#16a34a'><b>+{imp['score_gain']}% Gain</b></font>"
            imp_p = Paragraph(f"&bull; <b>{imp['rule_name']}</b> ({imp['category']}) &mdash; {gain_txt}: <i>{imp['recommendation']}</i>", body_style)
            story.append(imp_p)
        story.append(Spacer(1, 4))

    # Mandatory Disclaimer
    disclaimer_text = "<font color='#64748b' size='7.5'><i>Indicative estimate based on rule compliance. Final decision rests with EAC/SEAC.</i></font>"
    story.append(Paragraph(disclaimer_text, body_style))
    story.append(Spacer(1, 10))

    # 4. MISSING MANDATORY STUDIES
    story.append(Paragraph("3. Mandatory Studies Checklist Audit", h2_style))
    if result.missing_studies:
        missing_items = []
        for study in result.missing_studies:
            missing_items.append([
                Paragraph("<font color='#dc2626'><b>&bull; MISSING:</b></font>", meta_label),
                Paragraph(f"<b>{study.title()}</b> &mdash; Mandatory study specified in EC guidelines was not identified in the application.", body_style)
            ])
        missing_table = Table(missing_items, colWidths=[80, 460])
        missing_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#fef2f2")),
            ('BOX', (0, 0), (-1, -1), 0.75, colors.HexColor("#fecaca")),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(missing_table)
    else:
        story.append(Paragraph("<font color='#16a34a'><b>&check; All Mandatory Studies Present:</b> The report covers all primary checklist baseline studies.</font>", body_style))
    story.append(Spacer(1, 10))

    # 4. ISSUES TABLE (WRAPPED, COLOUR-CODED, EXCLUDING DISMISSED ISSUES)
    story.append(Paragraph("3. Flagged Inconsistencies & Contradictions", h2_style))

    active_issues = [i for i in result.issues if getattr(i, "reviewer_decision", None) != "Dismissed"]
    dismissed_count = len(result.issues) - len(active_issues)
    if dismissed_count > 0:
        story.append(Paragraph(f"<font color='#64748b' size='8'><i>Note: {dismissed_count} flagged issue(s) dismissed by reviewer upon technical verification and excluded from this formal report.</i></font>", body_style))
        story.append(Spacer(1, 4))

    if active_issues:
        # Columns: # (22), Category (78), Severity (55), Description (165), Page (60), Evidence (160) = 540 pt
        headers = [
            Paragraph("#", table_header),
            Paragraph("Category", table_header),
            Paragraph("Severity", table_header),
            Paragraph("Description", table_header),
            Paragraph("Page", table_header),
            Paragraph("Evidence / Quote", table_header),
        ]
        table_rows = [headers]

        table_styles = [
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0f172a")),
            ('ALIGN', (0, 0), (0, -1), 'CENTER'),
            ('ALIGN', (2, 0), (2, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('LEFTPADDING', (0, 0), (-1, -1), 5),
            ('RIGHTPADDING', (0, 0), (-1, -1), 5),
        ]

        for idx, issue in enumerate(active_issues):
            row_num = idx + 1
            
            # Severity color format
            sev = issue.severity.upper()
            if sev in ("CRITICAL", "HIGH"):
                sev_html = "<font color='#991b1b'><b>CRITICAL</b></font>"
                sev_bg = colors.HexColor("#fee2e2")
            elif sev in ("MAJOR", "MEDIUM"):
                sev_html = "<font color='#9a3412'><b>MAJOR</b></font>"
                sev_bg = colors.HexColor("#ffedd5")
            else:
                sev_html = "<font color='#166534'><b>MINOR</b></font>"
                sev_bg = colors.HexColor("#dcfce7")

            p_val = issue.page_number or issue.evidence_page or "N/A"
            q_val = issue.quote or issue.evidence_text or "N/A"

            row = [
                Paragraph(str(row_num), table_cell),
                Paragraph(f"<b>{issue.category}</b>", table_cell),
                Paragraph(sev_html, table_cell),
                Paragraph(issue.description, table_cell),
                Paragraph(p_val, table_cell),
                Paragraph(q_val, table_cell),
            ]
            table_rows.append(row)

            # Apply severity background tint to Severity cell
            table_styles.append(('BACKGROUND', (2, row_num), (2, row_num), sev_bg))
            
            # Alternate row background
            if row_num % 2 == 0:
                table_styles.append(('BACKGROUND', (0, row_num), (1, row_num), colors.HexColor("#f8fafc")))
                table_styles.append(('BACKGROUND', (3, row_num), (-1, row_num), colors.HexColor("#f8fafc")))

        issues_table = Table(table_rows, colWidths=[22, 78, 55, 165, 60, 160])
        issues_table.setStyle(TableStyle(table_styles))
        story.append(issues_table)
    else:
        story.append(Paragraph("<font color='#16a34a'><b>No active discrepancies flagged in this report.</b></font>", body_style))
    story.append(Spacer(1, 12))

    # 5. FOLLOW-UP QUESTIONS SECTION (ONE PER ACTIVE ISSUE)
    story.append(Paragraph("4. Follow-up Clarification Questions for Project Applicant", h2_style))
    story.append(Paragraph("<font color='#64748b' size='8'>Formulated queries requiring formal clarification from the project proponent:</font>", body_style))
    story.append(Spacer(1, 6))

    questions_found = False
    for idx, issue in enumerate(active_issues):
        if issue.follow_up_question and issue.follow_up_question.strip():
            questions_found = True
            q_num = idx + 1
            page_cite = f" [{issue.evidence_page}]" if issue.evidence_page else ""
            q_text = (
                f"<b>Query {q_num} ({issue.category}{page_cite}):</b> "
                f"{issue.follow_up_question}"
            )
            q_box = Table([[Paragraph(q_text, question_item)]], colWidths=[540])
            q_box.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
                ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ('LEFTPADDING', (0, 0), (-1, -1), 8),
                ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ]))
            story.append(q_box)
            story.append(Spacer(1, 4))

    if not questions_found:
        story.append(Paragraph("<i>No follow-up questions required for this application.</i>", body_style))

    # Build PDF with NumberedCanvas to ensure persistent footer
    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer.getvalue()
