[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50

[theme]
primaryColor = "#10b981"
backgroundColor = "#07120e"
secondaryBackgroundColor = "#0d241b"
textColor = "#f1f5f9"
font = "sans serif"

[client]
toolbarMode = "minimal"
